### ISSUE TITLE
Fix sudo npm install

### ISSUE THREAD

**Issue by Munter** [h5bp/lazyweb-requests#158]
There are a lot of references out there on the web that tell people to just sudo if a global module install fails. This is really bad practice. The culprit is usually a bad installer, making npm require super user access rights because the globally installed modules aren't in a user writable directory.

Please to be fixing all node installers and all references that tell people to do super user overrides when installing global packages.

**Comment by austinpray** [comment]
I am helping [the roots guys](http://roots.io/) implement a wordpress starter theme that makes heavy use of gulp and bower. The Wordpress community is pretty ignorant to all things node. If you go on the http://discourse.roots.io/ you can see people are very frequently having trouble. A lot of the issues stem from installing node incorrectly and using sudo with npm.

As a first step to solve their problem and this lazyweb issue I would propose creating a little informational webpage that explains the generally accepted best-practice for installing node. Kind of in the spirit of http://browsehappy.com/ and websites like it. This way we can toss this link around instead of having a million different opinions floating around. I would be more than happy to do this, but I need help building a coherent and peer-reviewed set of instructions. 

So my question is: what *is* the proper way for a newbie to install node?

I personally use nvm for all my node installs on both dev and prod. Obviously people can't just install node from the node website otherwise their permissions will be messed up. I agree with @Munter about avoiding messing with permissions.

**Comment by kevva** [comment]
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by renatomartins** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions
I used to use `sudo` to install global packages, but since I saw this page, I've been using `npm config set prefix '~/.local'`as soon as I install `node`.

**Comment by paulirish** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions is the right doc. 

any improvements to that page should just PR this: https://github.com/npm/docs/blob/master/content/getting-started/fixing-npm-permissions.md
