### ISSUE TITLE
Browser-based non-linear video editor

### ISSUE THREAD

**Issue by stuartpb** [h5bp/lazyweb-requests#198]
Granted, I understand that decoding, compositing, and re-encoding video is a complex and processor-intensive operation, but every open-source NLVE I've come across seems to have dedicated 90% of its effort to unrelated tasks, like re-inventing its own cross-platform UI toolkit with the ability to display _frames from a video_ to the screen while only crashing after 30% of user interactions. Features pertaining to _actually editing the video_ appear to have been secondary concerns.

What I want is a lightweight single-page-app that lets the user pick a set of files from their system to be read as `Blob`s, presents them via `<video>` for previewing clips and arrangement, and allows for previewing some effects using a technique like @brianchirls's [Seriously.js](https://github.com/brianchirls/Seriously.js). The production of the final video file could then be handed off to something like a complex `ffmpeg` command (or series of commands creating and compositing intermediate clips).

**Comment by brianchirls** [comment]
@stuartpb There's a great presentation about an attempt to do something like what you're proposing. Slides and video here:
https://2018.cascadiajs.com/speakers/megan-slater/

I'm doing quite a bit of research and work and hope to be able to release something in a few months that's more audio-focused. But there seem to be two major challenges:

- Precise timing of playback from multiple sources
- Encoding

Both of these are much, much easier with audio than video because the amount of data per second is orders of magnitude smaller for audio than video and because the Web Audio API provides sample-accurate timing.

Audio and video media elements are controlled in separate threads because they need to account for delays in reading from the network or even from the local cache. So if you try to synchronize multiple elements, it's not going to be perfectly accurate or reliable. The Web Audio API allows you to load and decode audio files in advance and send them over to the audio control thread with precise timing information. (Though you have to engage in memory management shenanigans so your device doesn't explode.) There is no equivalent for video at this point.

I suppose you could shift some of the work off to a server (or another process if you're using electron), but that's difficult and bandwidth- and CPU-intensive. Unless you don't care about precise timing, in which case the problem gets much easier.
