### ISSUE TITLE
A syntax for declaring a dependency on an external file

### ISSUE THREAD

**Issue by Munter** [h5bp/lazyweb-requests#201]
**The problem:** In order to create rich UI's using components in JavaScript, the javascript will often need to reference external files, like html templates, css files, images, svg's etc. Most current loader/bundler solutions overload the require/import syntax, letting you `import image from 'path/to/image.png';`. This overloading of imports to suddenly not always be a JS module leaks into the abstraction and configuration of all tools, breaks interoperability of the code etc.

What if there was a new syntax that allowed to specify a dependency on an external file, and at the same time save the location of the file to a local variable you could use in your JS runtime?

**Example**

```js
import ImageComponent from 'Image';
importExternal imageUrl from 'path/to/image.png';

assert(typeof imageUrl === 'string');

return function (props) {
  return <img src={imageUrl} {...props} />;
};
```

Such a syntax would still be possible to statically analyse, but it wouldn't overload the existing `require` or `import` statements, which could make frontend components like these capable of being run across multiple environments without crazy hacks to undo the overloading.

Module loaders and bundlers could still hook into the information present here and do post-processing that would change how assets are shuffled around through bundling, hashing etc.

In Assetgraph we previously used `GETSTATICURL(...)` to pick up such external references in the dependency graph, which required a runtime definition of this function: 

```js
window.GETSTATICURL = function (url) { // , placeHolderValue1, placeHolderValue2, ...
  var placeHolderValues = Array.prototype.slice.call(arguments, 1);
  return url.replace(/\*\*?|\{[^\}]*\}/g, function () {
    return placeHolderValues.shift();
  });
};
```

Since then we have extended our ability to pick up external file references from for example `fetch()`, but we still have an issue with picking up external file references that are just strings. The current solution is to pick up syntax like `'stringLiteral'.toString('url')`, which doesn't require any runtime function definition and is minifier safe, but is extremely ugly.

Obviously all sort of static analysis tools could benefit from the extra semantics of defining an a dependency on an external file, which is not a JS module, without breaking `import` semantics

**Comment by jhnns** [comment]
👍 for bringing up this discussion. A consistent handling of non-JS assets is still an open question in the frontend eco system. We had a lot of these discussions in the webpack community (https://github.com/webpack/webpack/issues/378 and https://github.com/webpack/concord) and even tried to reach out to @substack, but it seems like the community hasn't got an answer on this so far.

Here are just some random thoughts:

- Why is `import` overloading worse than introducing a new non-standard keyword? The overloaded import statement is also statically analyzable
- Depending on the asset, there might be use-cases where you want to examine different properties of the asset, like image dimensions, etc.
- It feels like the https://github.com/whatwg/loader spec goes into the direction of making overloading `import` possible. If the loader configuration is known at build time, a bundler could do the heavy-lifting at build time. In case, node manages to implement the ES2015 module and the loader spec, it would even outweigh the compatibility argument.

---

@substack also declines the overloading of `require()` and promotes the way of making everything "node-compatible". A bundler would then need to inspect the AST to prepare the bundle for client-side usage. Your example would then look like:

```javascript
import getImageUrl from "get-image-url";
const imageUrl = getImageUrl("path/to/image.png");
```

This is basically how the browserify community is handling it. Another example of this is [sheetify](https://github.com/stackcss/sheetify):

```javascript
const prefix = css`
  :host > h1 {
    text-align: center;
  }
```

I really like that approach, but I feel like it's not that different than overloading `require()` or `import()`. Both require static analysis to perform this optimization. Overloading `import()` even feels a little simpler because it makes the boundary clear. Inspecting the AST can be error prone/impossible if the code is too dynamic. The true downside of overloading `require()` was its incompatibility with node. But with the advance of the loader spec, this could change.

---

However, recent trends are towards putting related things into the same file (like JSX, [Vue](https://vuejs.org/) and all the CSS-in-JS libraries). I don't know if that is just a trend, but I feel like the main motivation behind this is the powerful ES2015 module spec. Treating HTML and CSS as JS brings modularity to HTML and CSS where is has been missing. It circumvents the global namespace of HTML and CSS with all its downsides. It also enables optimizations such as tree-shaking.

---

There's also a technique in the middle between overloading `import()` (webpack) and inspecting the AST (browserify). I'd call it ahead-of-time evaluation and it means that you evaluate a part of the bundle at build time in order to optimize/prepare assets. It's similar like inspecting the AST, but more powerful and easier to reason about (at least for me). It's used in the [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) in order to replace the generated CSS with stylesheet URLs.

On first sight, this might seem hacky, but I begin to like the idea because it enables a lot of interoperable bundling/optimization techniques without conceptual/architectural overhead as introduced by webpack loaders (and browserify transforms to some degree). It's pretty similar to @substack 's original idea (to make everything node compatible), but without involving the AST which feels a little bit error prone and limiting to me. The downside of this is that you should not have code with side-effects in the top-level scope of your module, but I think that is an anti-pattern anyway and only necessary in the very first module.

**Comment by jhnns** [comment]
The [asset references](https://github.com/sebmarkbage/ecmascript-asset-references) proposal could be something in the right direction.

**Comment by Munter** [comment]
@jhnns I agree. I've been following that proposal with great interest
