### ISSUE TITLE
A SEO Optimization Exension for Chrome

### ISSUE THREAD

**Issue by gnarf** [h5bp/lazyweb-requests#41]
So far, the best SEO tool I've found is [SenSEO](https://addons.mozilla.org/en-US/firefox/addon/senseo/), which is a firefox addon.  

Paul has suggested that this might be a great fit for a Dev tools [audit extenstion](http://smus.com/extending-chrome-developer-tools)

I'd like to see almost all of the features that SenSEO has in a Chrome Extension, no matter how we make it happen.

**Comment by arthurvr** [comment]
This is a wonderful idea. I know I used SenSEO when I was using Firefox. These days I switched over to Chrome, and never found a good alternative. If there aren't any good alternatives yet, I'm really willing to work on this.

@gnarf I'm wondering if you ever found anything? This issue was opened back in 2011 so...

> @gnarf37 have you tried http://www.omiod.com/meta-inspector.php

I would like to see it open source. Is it? I would like to see this open source as it's on the meanwhile a great opportunity to discuss best-practices. Also this isn't an audit extension, which would we really nice.
